import assert from 'node:assert/strict';
import {writeFileSync,readFileSync,existsSync,mkdirSync} from 'node:fs';
const pages=await(await fetch('http://127.0.0.1:9222/json')).json();
const ws=new WebSocket(pages.find(x=>x.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);
let id=0;const pending=new Map(),errors=[];
ws.onmessage=e=>{const x=JSON.parse(e.data);if(x.id){const p=pending.get(x.id);pending.delete(x.id);x.error?p.reject(Error(x.error.message)):p.resolve(x.result)}else if(x.method==='Runtime.exceptionThrown')errors.push(x.params.exceptionDetails.text+': '+x.params.exceptionDetails.exception?.description)};
const send=(method,params={})=>new Promise((resolve,reject)=>{const i=++id;pending.set(i,{resolve,reject});ws.send(JSON.stringify({id:i,method,params}))});
const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value};
const waitFor=async expr=>{for(let i=0;i<100;i++){if(await evaluate(expr))return;await new Promise(r=>setTimeout(r,100))}throw Error('Timed out: '+expr)};
const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
const downloadPath='/tmp/gentle-download-'+Date.now();mkdirSync(downloadPath);await send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath});
await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:'http://127.0.0.1:5173/'});await waitFor(`document.querySelector('#progress')?.textContent.includes('Complete')`);
assert.match(await evaluate(`document.querySelector('#results').textContent`),/Dimensions by degree/);
for(const tab of ['cohomology','homology','cyclic','structure','all','surface','lie','checks','operations']){await click(`[data-tab="${tab}"]`);assert.ok(await evaluate(`document.querySelector('#results').textContent.length>50`))}
await click('#run-operation');await waitFor(`!!document.querySelector('.operation-result')`);
await click('[data-tab="all"]');await click('#formula-query');await waitFor(`document.querySelector('#formula-result').textContent.includes('Degree 100')`);await click('[data-tab="lie"]');await click('#lie-query');await waitFor(`document.querySelector('#lie-result').textContent.includes('Derived-series')`);await click('[data-tab="overview"]');await send('Page.captureScreenshot',{format:'png'}).then(x=>writeFileSync('/tmp/gentle-desktop.png',Buffer.from(x.data,'base64')));
await evaluate(`document.querySelector('#examples').value='dual';document.querySelector('#examples').dispatchEvent(new Event('change'))`);await click('#compute');await waitFor(`document.querySelector('#progress').textContent.includes('Complete')`);await click('[data-tab="operations"]');await evaluate(`document.querySelector('#op-type').value='bracket';document.querySelector('#op-type').dispatchEvent(new Event('change'))`);await evaluate(`document.querySelector('#op-p').value='1';document.querySelector('#op-p').dispatchEvent(new Event('change'))`);await evaluate(`document.querySelector('#right-0').value='0';document.querySelector('#right-1').value='1'`);await click('#run-operation');await waitFor(`!!document.querySelector('.operation-result')`);assert.match(await evaluate(`document.querySelector('.formula').textContent`),/1 h/);
await click('#theme');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await click('[data-tab="all"]');await click('#formula-query');await waitFor(`document.querySelector('#formula-result').textContent.includes('Degree 100')`);await click('[data-tab="lie"]');await click('#lie-query');await waitFor(`document.querySelector('#lie-result').textContent.includes('Derived-series')`);await click('[data-tab="overview"]');await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true}).then(x=>writeFileSync('/tmp/gentle-mobile.png',Buffer.from(x.data,'base64')));assert.ok(await evaluate(`document.documentElement.scrollWidth<=window.innerWidth`),'mobile has horizontal overflow');
await click('#new');await click('[data-tool="vertex"]');
// Use actual browser pointer events on the SVG, not synthetic application functions.
const at=async(x,y)=>{const p=await evaluate(`(()=>{const p=document.querySelector('#quiver').createSVGPoint();p.x=${x};p.y=${y};const s=p.matrixTransform(document.querySelector('#quiver').getScreenCTM());return {x:s.x,y:s.y}})()`);await send('Input.dispatchMouseEvent',{type:'mousePressed',x:p.x,y:p.y,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:p.x,y:p.y,button:'left',clickCount:1})};
await at(240,220);await at(560,220);assert.equal(await evaluate(`document.querySelectorAll('[data-vertex]').length`),2);await click('[data-tool="arrow"]');await at(240,220);await at(560,220);assert.equal(await evaluate(`document.querySelectorAll('[data-arrow]').length`),1);await click('#undo');assert.equal(await evaluate(`document.querySelectorAll('[data-arrow]').length`),0);await click('#redo');assert.equal(await evaluate(`document.querySelectorAll('[data-arrow]').length`),1);
await click('#compute');await waitFor(`document.querySelector('#progress').textContent.includes('Complete')`);await click('#export');assert.equal(await evaluate(`document.querySelector('#export-tex').disabled`),false);await click('#export-tex');for(let i=0;i<50&&!existsSync(downloadPath+'/gentle-calculus.tex');i++)await new Promise(r=>setTimeout(r,100));assert.ok(readFileSync(downloadPath+'/gentle-calculus.tex','utf8').includes('\\section{Cohomology ring presentation}'));await click('#export-quiver');for(let i=0;i<50&&!existsSync(downloadPath+'/gentle-quiver.json');i++)await new Promise(r=>setTimeout(r,100));assert.equal(JSON.parse(readFileSync(downloadPath+'/gentle-quiver.json','utf8')).quiver.arrows.length,1);await click('#close-modal');
// Characteristic validation and cancellation must not produce apparent zero results.
await evaluate(`document.querySelector('#characteristic').value='custom';document.querySelector('#characteristic').dispatchEvent(new Event('change'));document.querySelector('#custom-prime').value='4';document.querySelector('#custom-prime').dispatchEvent(new Event('change'))`);await click('#compute');await waitFor(`document.querySelector('#progress').textContent.includes('prime')`);assert.ok(!(await evaluate(`document.querySelector('#results').textContent`)).includes('Dimensions by degree'));
await evaluate(`document.querySelector('#characteristic').value='0';document.querySelector('#characteristic').dispatchEvent(new Event('change'));document.querySelector('#compute').click();document.querySelector('#cancel').click()`);await waitFor(`document.querySelector('#progress').textContent.includes('cancelled')`);await click('#compute');await waitFor(`document.querySelector('#progress').textContent.includes('Complete')`);
assert.deepEqual(errors,[]);console.log('Browser smoke checks passed: tabs, exact bracket, editor pointer input, undo/redo, mobile overflow, theme, export availability.');ws.close();
