export function texEscape(value){const map={'\\':'\\textbackslash{}','{':'\\{','}':'\\}','$':'\\$','&':'\\&','#':'\\#','_':'\\_','%':'\\%','~':'\\textasciitilde{}','^':'\\textasciicircum{}'};return String(value).replace(/[\\{}$&#_%~^]/g,c=>map[c]).replace(/[αβγδεζηθικλμνξοπρστυφχψωε↦·∞≥→↔−²¹⊕]/g,c=>'\\ensuremath{'+({'α':'\\alpha','β':'\\beta','γ':'\\gamma','δ':'\\delta','ε':'\\varepsilon','ζ':'\\zeta','η':'\\eta','θ':'\\theta','ι':'\\iota','κ':'\\kappa','λ':'\\lambda','μ':'\\mu','ν':'\\nu','ξ':'\\xi','ο':'o','π':'\\pi','ρ':'\\rho','σ':'\\sigma','τ':'\\tau','υ':'\\upsilon','φ':'\\phi','χ':'\\chi','ψ':'\\psi','ω':'\\omega','↦':'\\mapsto','·':'\\cdot','∞':'\\infty','≥':'\\geq','→':'\\to','↔':'\\leftrightarrow','−':'-','²':'^2','¹':'^1','⊕':'\\oplus'}[c])+'}').replace(/[ΓΔΘΛΞΠΣΥΦΨΩ]/g,c=>'\\ensuremath{'+({'Γ':'\\Gamma','Δ':'\\Delta','Θ':'\\Theta','Λ':'\\Lambda','Ξ':'\\Xi','Π':'\\Pi','Σ':'\\Sigma','Υ':'\\Upsilon','Φ':'\\Phi','Ψ':'\\Psi','Ω':'\\Omega'}[c])+'}').replace(/[₀₁₂₃₄₅₆₇₈₉ₚₙ₊]/g,c=>'\\ensuremath{_{'+({'₀':'0','₁':'1','₂':'2','₃':'3','₄':'4','₅':'5','₆':'6','₇':'7','₈':'8','₉':'9','ₚ':'p','ₙ':'n','₊':'+'}[c])+'}}')}
const mathText=s=>`\\text{${texEscape(s)}}`;
const heading=s=>`\\texorpdfstring{${texEscape(s)}}{${String(s).replace(/[\\{}$&#_%~^]/g,' ')}}`;
const scalar=s=>{const [a,b]=s.split('/');return b?`\\frac{${a}}{${b}}`:a};
function derivedLatex(d){
 const out=['\\section{Complete derived invariant}', 'Amiot--Plamondon--Schroll, Theorem 7.4. '+`\\href{https://doi.org/10.1007/s00029-022-00822-x}{Source paper}.`, 'Boundary windings use the APS convention $w=n-m$, opposite to the TT surface convention. Unmarked boundaries represent punctures.'];
 for(const [i,c] of d.components.entries()){
  out.push(`\\subsection{Connected component ${i+1}}`,`Vertices: ${c.vertices.map(texEscape).join(', ')}. Genus ${c.genus}; ${c.ordinaryBoundaries} marked boundaries; ${c.punctures} punctures.`, `Classification branch: ${texEscape(c.branch)}.`, ...(c.gcd===null?[]:[`Genus-one gcd: $${c.gcd}$.`]),...(c.arf===null?[]:[`Arf invariant: $${c.arf}$.`]),'\\begin{longtable}{rrr}Marked points & Forbidden length & APS winding \\\\ \\hline',...c.boundaries.map(b=>`${b.markedPoints} & ${b.forbiddenLength} & ${b.winding} \\\\`),'\\end{longtable}');
  out.push('Spanning-tree cycle basis (not necessarily symplectic):');
  for(const curve of c.curves)out.push(`${texEscape(curve.name)}: winding $${curve.winding}$; edge walk ${curve.walk.map(e=>`${texEscape(e.edge)} (${e.from} to ${e.to})`).join(', ')}; local turns $(${curve.turns.join(',')})$.`);
  if(c.intersection.length)out.push('Intersection matrix over $\\mathbb F_2$ (rows on separate lines):','\\begin{flushleft}\\ttfamily',...c.intersection.map(row=>row.join(' ')+'\\\\'),'\\end{flushleft}');
  if(c.quadratic)out.push('Quadratic refinement $q([\\gamma])=w(\\gamma)/2+1\\pmod 2$. Reduced symplectic pairs $(q(a_i),q(b_i))$: '+c.quadratic.pairs.map(p=>`$(${p.qa},${p.qb})$`).join(', ')+'. The quadratic refinement vanishes on the radical.');
 }
 out.push('\\subsection{Consistency checks}','\\begin{itemize}',...d.checks.map(c=>'\\item '+texEscape(c)),'\\end{itemize}');return out.join('\n\n');
}
function presentationLatex(q){const arrow=id=>q.arrows.find(a=>a.id===id)?.label||id;return ['\\section{'+heading(q.name||'Algebra')+'}', 'Vertices: '+q.vertices.map(v=>texEscape(v.label)).join(', ')+'.',...q.arrows.map(a=>`Arrow ${texEscape(a.label)}: ${texEscape(q.vertices.find(v=>v.id===a.source).label)} to ${texEscape(q.vertices.find(v=>v.id===a.target).label)}.\\par`),'Zero relations (travel order): '+(q.relations.map(r=>r.map(id=>texEscape(arrow(id))).join(' then ')+' = 0').join('; ')||'none')+'.'].join('\n\n')}
function comparisonLatex(c){return ['\\section{Derived equivalence comparison}',`${texEscape(c.left.name||'Left algebra')} versus ${texEscape(c.right.name||'Right algebra')}. Characteristics: ${texEscape(c.left.characteristic)} and ${texEscape(c.right.characteristic)}.`,texEscape(c.result.reason),presentationLatex(c.right.quiver),...(c.result.right?[derivedLatex(c.result.right)]:[])].join('\n\n')}
export function latexDerivedReport(q,d,comparison=null){return [String.raw`\documentclass[11pt]{article}
\usepackage{fontspec,unicode-math,amsmath,longtable,geometry,hyperref}
\setmainfont{Latin Modern Roman}
\setmathfont{Latin Modern Math}
\geometry{margin=25mm}
\begin{document}`,presentationLatex(q),derivedLatex(d),...(comparison?[comparisonLatex(comparison)]:[]),'\\end{document}'].join('\n\n')+'\n'}
export function latexReport(q,r,operations=[]){
 const out=[String.raw`\documentclass[11pt]{article}
\usepackage{fontspec}
\usepackage{unicode-math}
\setmainfont{Latin Modern Roman}
\setmathfont{Latin Modern Math}
\usepackage{amsmath,longtable,geometry,hyperref}
\geometry{margin=25mm}
\newcommand{\HH}{\operatorname{HH}}
\newcommand{\HC}{\operatorname{HC}}
\begin{document}`,`\\title{${texEscape(q.name||'Gentle algebra')}\\\\Tamarkin--Tsygan calculation}`,`\\author{Gentle workspace, engine ${texEscape(r.engine)}}`,'\\date{\\today}','\\maketitle','\\section{Presentation and conventions}',`We work over ${r.characteristic==='0'?'$\\mathbb{Q}$':`$\\mathbb{F}_{${r.characteristic}}$`}. Paths are written in travel order, from left to right. The source paper uses the reverse writing convention. All displayed computations use exact arithmetic.`,
 `Vertices: ${q.vertices.map(v=>mathText(v.label)).map(s=>`$${s}$`).join(', ')}.`,
 '\\begin{longtable}{lll}Arrow & Source & Target \\\\ \\hline',...q.arrows.map(a=>`${texEscape(a.label)} & ${texEscape(q.vertices.find(v=>v.id===a.source).label)} & ${texEscape(q.vertices.find(v=>v.id===a.target).label)} \\\\`),'\\end{longtable}',
 q.relations.length?'Zero relations: '+q.relations.map(t=>`$${t.map(id=>mathText(q.arrows.find(a=>a.id===id).label)).join('\\cdot')}=0$`).join(', ')+'.':'There are no zero relations.',
 `The algebra has dimension $${r.algebraDimension}$. Its global dimension is $${r.structure.globalDimension==='∞'?'\\infty':r.structure.globalDimension}$.`,
 '\\section{Dimensions}','\\begin{longtable}{rrrr}$n$ & $\\dim\\HH^n$ & $\\dim\\HH_n$ & $\\dim\\HC_n$ \\\\ \\hline',...r.rows.map(x=>`${x.degree} & ${x.hhCo} & ${x.hhHo} & ${x.hc} \\\\`),'\\end{longtable}',
 '\\section{Representatives}', texEscape(r.convention), 'Representatives use the normalized bar resolution relative to the vertex algebra $E$. Unlisted cochain values are zero. The notation $a_0[a_1|\\cdots|a_n]$ denotes a relative normalized chain. In cyclic homology, $C_k$ identifies a summand of the total complex.'];
 for(const row of r.rows)for(const [name,basis,sym] of [['Cohomology',row.coBasis,`h^{${row.degree}}`],['Homology',row.hoBasis,`z_{${row.degree}}`],['Cyclic homology',row.cyBasis,`c_{${row.degree}}`]]){out.push(`\\subsection{${name}, degree ${row.degree}}`);if(!basis)out.push('Dimension computed by the circuit formulas. Bar representatives were not materialized due to a resource limit.');else if(!basis.length)out.push('This group is zero.');else basis.forEach((b,i)=>{out.push(`\\noindent Basis class $${name==='Cohomology'?`h^{${row.degree}}_{${i+1}}`:`${name==='Homology'?'z':'c'}_{${row.degree},${i+1}}`}$:`, '\\begin{flushleft}');for(const term of b)out.push(`$${scalar(term.coefficient)}$\\quad ${texEscape(term.term)}\\par`);out.push('\\end{flushleft}')})}
 out.push('\\section{Operations}');if(!operations.length)out.push('No operations were recorded.');for(const [i,o] of operations.entries()){out.push(`\\subsection{${i+1}. ${texEscape(o.type)}}`,`Input degrees: $${o.p}${o.type==='connes'?'':`, ${o.q}`}$. Coefficients in the displayed bases: $(${o.left.map(scalar).join(',')})$${o.type==='connes'?'':` and $(${o.right.map(scalar).join(',')})$`}.`,`Output degree: $${o.result.degree}$. Coordinates: $(${o.result.coefficients.map(scalar).join(',')})$.`, '\\begin{flushleft}');for(const term of o.result.representative)out.push(`$${scalar(term.coefficient)}$\\quad ${texEscape(term.term)}\\par`);if(!o.result.representative.length)out.push('$0$');out.push('\\end{flushleft}');if(o.outputBasis){out.push('Output basis representatives:');for(const [j,b] of o.outputBasis.basis.entries()){out.push(`Basis class ${j+1}:`);for(const term of b)out.push(`$${scalar(term.coefficient)}$\\quad ${texEscape(term.term)}\\par`)}}}
 out.push('\\section{All-degree cohomology families}');
 for(const f of r.families||[])out.push(`\\paragraph{${texEscape(f.name)}} Type ${f.type}. ${f.step?`Degrees $${f.degree}+${f.step}j$ for $j\\geq 0$.`:`Degree $${f.degree}$.`} Multiplicity ${f.multiplicity}. ${texEscape(f.description)}`);
 out.push('\\section{Cohomology ring presentation}');
 for(const [i,component] of (r.ring||[]).entries()){out.push(`\\subsection{Component ${i+1}}`,texEscape(component.description));for(const g of component.generators)out.push(`${texEscape(g.name)}, degree $${g.degree}$.`);if(!component.exceptional)out.push('Quadratic products not forced to zero: '+(component.allowedProducts.map(texEscape).join(', ')||'none')+'.');for(const e of component.equalities)out.push(texEscape(e)+'.')}
 if(r.structure.ribbon){const rb=r.structure.ribbon;out.push('\\section{Marked surface and AAG invariant}',`Total genus ${rb.genus}; ${rb.components} connected component(s); ${rb.boundaries.length} boundary components; ${rb.markedPoints} marked points. Euler characteristic ${rb.euler}.`,'\\begin{longtable}{rrrr}Boundary & Marked points & Forbidden length & Winding \\\\ \\hline',...rb.boundaries.map((b,i)=>`${i+1} & ${b.markedPoints} & ${b.forbiddenLength} & ${b.winding} \\\\`),'\\end{longtable}');for(const a of rb.aag)out.push(`$\\phi_A(${a.pair.join(',')})=${a.multiplicity}$.`);out.push('All other entries vanish.');for(const [i,t] of rb.threads.entries())out.push(`Ribbon vertex ${i+1}: ${texEscape(t.label)}. Incident edges in cyclic order: ${t.visits.map(texEscape).join(', ')}. The marked sector closes this linear order.`)}
 if(r.rows[0].deRham!==undefined){out.push('\\section{Connes and de Rham dimensions}','\\begin{longtable}{rrr}$n$ & $\\operatorname{rank} B_n$ & $\\dim H^{\\mathrm{dR}}_n$ \\\\ \\hline',...r.rows.map(x=>`${x.degree} & ${x.connesRank} & ${x.deRham} \\\\`),'\\end{longtable}')}
 if(r.lie){out.push('\\section{The Lie algebra in degree one}',`Dimension ${r.lie.dimension}, center dimension ${r.lie.centerDimension}. Derived-series dimensions: ${r.lie.derived.join(', ')}.`,r.lie.solvable?'This Lie algebra is solvable.':'The derived series stabilizes at a nonzero ideal.');for(let i=0;i<r.lie.dimension;i++)for(let j=0;j<r.lie.dimension;j++)out.push(`$[h^1_{${i+1}},h^1_{${j+1}}]$ has coordinates $(${r.lie.table[i][j].map(scalar).join(',')})$.`)}
 out.push('\\section{Further structural data}',`Graph Euler characteristic ${r.structure.euler}; cycle rank ${r.structure.cycleRank}.`,'Path basis: '+r.paths.map(texEscape).join(', ')+'.','Maximal permitted paths: '+r.structure.permitted.map(texEscape).join(', ')+'.','Maximal finite forbidden paths: '+r.structure.forbidden.map(texEscape).join(', ')+'.','Complete primitive circuits: '+r.structure.cycles.map(c=>texEscape(c.label)+` (length ${c.length})`).join(', ')+'.','Path-count matrix (rows are sources, columns targets in the input vertex order):',`\\[\\begin{pmatrix}${r.structure.cartan.map(row=>row.join(' & ')).join(' \\\\ ')}\\end{pmatrix}\\]`);
 for(const row of r.rows){if(row.connesMatrix){out.push(`\\subsection{Connes matrix in degree ${row.degree}}`);for(const [i,cs] of row.connesMatrix.entries())out.push(`$B(z_{${row.degree},${i+1}})$ has coordinates $(${cs.map(scalar).join(',')})$ in degree ${row.degree+1}.`)}if(row.deRhamBasis){out.push(`De Rham basis coordinates in $\\HH_{${row.degree}}$: `+row.deRhamBasis.map(cs=>`$(${cs.map(scalar).join(',')})$`).join(', ')+'.')}}
 for(const g of r.additionalGroups||[]){out.push(`\\section{Additional Bardzell ${g.kind==='co'?'cohomology':'homology'}, degree ${g.degree}}`,`Dimension ${g.dimension}.`);for(const [i,b] of g.basis.entries()){out.push(`Basis class ${i+1}:`);for(const term of b)out.push(`$${scalar(term.coefficient)}$\\quad ${texEscape(term.term)}\\par`)}}
 for(const f of r.formulaQueries||[])out.push(`Formula query in degree ${f.degree}: cohomology dimension ${f.co}, homology dimension ${f.hh}, cyclic homology dimension ${f.hc}, de Rham dimension ${f.deRham}, Connes rank ${f.bRank}.`);
 if(r.derived)out.push(derivedLatex(r.derived));
 if(r.comparison)out.push(comparisonLatex(r.comparison));
 out.push('\\section{Checks}', '\\begin{itemize}', ...r.checks.map(c=>`\\item ${texEscape(c)}`),'\\end{itemize}', '\\section{Scope and source}',`The displayed range is $0\\le n\\le ${r.maxDegree}$. ${r.mode==='formulas'?'Dimensions were computed by circuit formulas; the bar-complex calculation exceeded its resource limit.':'Adjacent differentials were included.'} No vanishing above this range is implied. Computation limits apply. All-degree families and ring and surface data are included when computed. Individual operations are evaluated in finite chain spaces, subject to resource limits. There is no symbolic polynomial parser or interactive surface-curve editor. These consistency checks do not replace independent mathematical review.`,
 'Source: C. Chaparro, S. Schroll, A. Solotar, M. Su\\\'arez-\\\'Alvarez, \\emph{The Hochschild cohomology and the Tamarkin--Tsygan calculus of gentle algebras}, \\href{https://arxiv.org/abs/2311.08003v4}{arXiv:2311.08003v4}.', '\\end{document}');return out.join('\n\n')+'\n';
}
